USE bryleigh;
INSERT INTO categories (category_name) VALUES ('Tops'),('Dresses'),('Outerwear'),('Bags'),('Shoes') ON DUPLICATE KEY UPDATE category_name=VALUES(category_name);
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Vintage Denim Jacket','Classic relaxed-fit denim jacket.',850.00,'Good',3,NULL,'active' FROM categories WHERE category_name='Outerwear' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Vintage Denim Jacket');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Floral Summer Dress','Light floral dress for sunny days.',650.00,'Like New',4,NULL,'active' FROM categories WHERE category_name='Dresses' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Floral Summer Dress');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Leather Crossbody Bag','Compact genuine leather crossbody bag.',1200.00,'Good',2,NULL,'active' FROM categories WHERE category_name='Bags' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Leather Crossbody Bag');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Preloved Sneakers','Everyday sneakers with plenty of life left.',950.00,'Fair',0,NULL,'active' FROM categories WHERE category_name='Shoes' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Preloved Sneakers');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Knit Cardigan','Soft neutral cardigan.',700.00,'Good',1,NULL,'active' FROM categories WHERE category_name='Tops' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Knit Cardigan');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Plaid Blazer','Smart plaid blazer for layering.',1100.00,'Like New',2,NULL,'active' FROM categories WHERE category_name='Outerwear' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Plaid Blazer');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Denim Shorts','Casual high-waist denim shorts.',450.00,'Good',5,NULL,'active' FROM categories WHERE category_name='Tops' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Denim Shorts');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Canvas Tote','Sturdy reusable canvas tote.',350.00,'Good',6,NULL,'active' FROM categories WHERE category_name='Bags' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Canvas Tote');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Ribbed Crop Top','Minimal ribbed cotton crop top.',300.00,'Like New',3,NULL,'active' FROM categories WHERE category_name='Tops' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Ribbed Crop Top');
INSERT INTO products (category_id,title,description,price,item_condition,stock,image_path,status) SELECT category_id,'Pleated Midi Skirt','Flowy pleated midi skirt.',575.00,'Good',2,NULL,'active' FROM categories WHERE category_name='Dresses' AND NOT EXISTS (SELECT 1 FROM products WHERE title='Pleated Midi Skirt');

