<?php
// Run from the project root: C:\xampp\php\php.exe database/seed_users.php
require __DIR__ . '/../includes/db.php';
$pdo->beginTransaction();
function seed_user(PDO $pdo, string $name, string $email, string $password, string $role): int { $s=$pdo->prepare('SELECT user_id FROM users WHERE email=?'); $s->execute([$email]); $id=$s->fetchColumn(); if ($id) { $u=$pdo->prepare('UPDATE users SET full_name=?, password_hash=?, role=? WHERE user_id=?'); $u->execute([$name,password_hash($password,PASSWORD_DEFAULT),$role,$id]); return (int)$id; } $u=$pdo->prepare('INSERT INTO users(full_name,email,password_hash,role) VALUES(?,?,?,?)'); $u->execute([$name,$email,password_hash($password,PASSWORD_DEFAULT),$role]); return (int)$pdo->lastInsertId(); }
$adminId=seed_user($pdo,'Admin User','admin@bryleigh.com','Admin123!','admin'); $customerId=seed_user($pdo,'Test Customer','customer@bryleigh.com','Customer123!','customer');
$products=$pdo->query('SELECT product_id,price FROM products ORDER BY product_id LIMIT 3')->fetchAll();
if (count($products) >= 3) { $statuses=[['pending','pending','not_shipped'],['paid','pending','shipped'],['paid','completed','delivered']]; foreach($statuses as $i=>$state) { $marker='seed-' . ($i+1); $check=$pdo->prepare('SELECT order_id FROM orders WHERE user_id=? AND payment_reference=?'); $check->execute([$customerId,$marker]); if($check->fetchColumn()) continue; $total=(float)$products[$i]['price']; $o=$pdo->prepare("INSERT INTO orders(user_id,total_amount,payment_method,payment_reference,delivery_option,payment_status,shipping_status,order_status,ship_name,ship_phone,ship_address,ship_city,ship_province,ship_zip,ship_region) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"); $o->execute([$customerId,$total,'GCash',$marker,'Standard',$state[0],$state[2],$state[1],'Test Customer','09170000000','1 Bryleigh Street','Manila','Metro Manila','1000','NCR']); $orderId=$pdo->lastInsertId(); $item=$pdo->prepare('INSERT INTO order_items(order_id,product_id,quantity,price_at_sale) VALUES(?,?,1,?)'); $item->execute([$orderId,$products[$i]['product_id'],$products[$i]['price']]); echo "Created sample order #$orderId ($marker)\n"; } }
$pdo->commit(); echo "Seeded/updated admin and customer accounts.\n";

